//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        public int idMensaje { get; set; }
        public string textoMensaje { get; set; }
        public string fecha { get; set; }
        public string emailRemitente { get; set; }


        public Mensajes(string texto, string fecha1, string email)
        {
            textoMensaje = texto;
            fecha = fecha1;
            emailRemitente = email;
        }


    }
}
