//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticias
    {
        public Noticias()
        {
        }

        public Noticias(DateTime? fechaNoticia, string textoNoticia, int? idAutor)
        {
            FechaNoticia = fechaNoticia;
            this.textoNoticia = textoNoticia;
            this.idAutor = idAutor;
        }

        public int idNoticia { get; set; }
        public Nullable<System.DateTime> FechaNoticia { get; set; }
        public string textoNoticia { get; set; }
        public Nullable<int> idAutor { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
