//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Noticias = new HashSet<Noticias>();
            this.Ventas = new HashSet<Ventas>();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios(string nomU, string pass, string pnom, string snom, string appat, string apmat, DateTime fecha, int tipo, string mail)
        {
            this.Noticias = new HashSet<Noticias>();
            this.Ventas = new HashSet<Ventas>();
            nombreUsuario = nomU;
            password = pass;
            pnombre = pnom;
            snombre = snom;
            apat = appat;
            amat = apmat;
            fechaRegistro = fecha;
            tipoUsuario = tipo;
            email = mail;
        }


        public Usuarios(int idUsuario, string nombreUsuario, string password, string pnombre, string snombre, string apat, string amat, DateTime fechaRegistro, int tipoUsuario, string email)
        {
            this.idUsuario = idUsuario;
            this.nombreUsuario = nombreUsuario;
            this.password = password;
            this.pnombre = pnombre;
            this.snombre = snombre;
            this.apat = apat;
            this.amat = amat;
            this.fechaRegistro = fechaRegistro;
            this.tipoUsuario = tipoUsuario;
            this.email = email;
        }

        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string password { get; set; }
        public string pnombre { get; set; }
        public string snombre { get; set; }
        public string apat { get; set; }
        public string amat { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int tipoUsuario { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Noticias> Noticias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
